version: '3.9'

services:
  mysql:
    image: mysql:8.0.38
    restart: unless-stopped
    networks:
      - carShow
    environment:
      MYSQL_ROOT_PASSWORD: Gudmord92!
      MYSQL_DATABASE: car_show
      MYSQL_USER: carShowDB
      MYSQL_PASSWORD: Gudmord92!
    ports:
      - "3307:3306"
    volumes:
      - db:/lib/mysql
  api:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
    networks:
      - carShow
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/car_show?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: carShowDB
      SPRING_DATASOURCE_PASSWORD: Gudmord92!

    stdin_open: true
    tty: true
networks:
  carShow:

volumes:
  db: