spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_show?createDatabaseIfNotExist=true
    username: root
    password: Gudmord92!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: a4e345d03623d6f34ac36c9dacab574caefb4d3210d110045483b18a03817764
  expiration: 7200000